extension ExperimentRegistry {
    /// Every experiment this build knows about, in ID order. Adding an experiment means adding its
    /// spec, regenerating the catalog, and adding its line here in the same change.
    public static let registrations: [ExperimentRegistration] = [
        ExperimentRegistration("LAB-001", fallback: "A normal app action browser runs without Siri or Apple Intelligence."),
        ExperimentRegistration("LAB-002", fallback: "In-app card and typed Shortcut remain complete; context resolution is explicitly unavailable."),
        ExperimentRegistration("LAB-003", fallback: "Manual recipe instructions and app action browser; no secret storage inside Shortcuts."),
        ExperimentRegistration("LAB-004", fallback: "Main-app state deck and static widget previews."),
        ExperimentRegistration("LAB-005", fallback: "In-app job panel and optional completion notification."),
        ExperimentRegistration("LAB-006", fallback: "Lexical in-app search with the same result model."),
        ExperimentRegistration("LAB-007", fallback: "Host-app file picker and paste action; extension not required for core build."),
        ExperimentRegistration("LAB-008", fallback: "File picker and explicit export preserve the full native document."),
        ExperimentRegistration("LAB-009", fallback: "Document browser with previews; provider remains disabled until qualified."),
        ExperimentRegistration("LAB-010", fallback: "Deterministic sample parser and manual editor clearly labeled as non-model paths."),
        ExperimentRegistration("LAB-011", fallback: "Local generation or manual workflow; no mandatory third-party key."),
        ExperimentRegistration("LAB-012", fallback: "Image picker plus OCR and manual fields."),
        ExperimentRegistration("LAB-013", fallback: "Import a caption fixture or annotate manually; unsupported languages are stated."),
        ExperimentRegistration("LAB-014", fallback: "Bilingual fixtures and editable side-by-side text."),
        ExperimentRegistration("LAB-015", fallback: "Deterministic fixture executor benchmarks the pipeline, marked as not inference."),
        ExperimentRegistration("LAB-016", fallback: "Copy an explicit continuation link or document."),
        ExperimentRegistration("LAB-017", fallback: "Local store plus manual document exchange."),
        ExperimentRegistration("LAB-018", fallback: "Local two-window simulation labeled as simulated; ordinary playback still works."),
        ExperimentRegistration("LAB-019", fallback: "Single-device conductor/client simulation with identical wire messages."),
        ExperimentRegistration("LAB-020", fallback: "The LAN adapter from Local Constellation supplies the same operation."),
        ExperimentRegistration("LAB-021", fallback: "Phone control pad and a Watch simulator preview."),
        ExperimentRegistration("LAB-022", fallback: "Manual distance slider or prerecorded synthetic measurements, prominently labeled."),
        ExperimentRegistration("LAB-023", fallback: "Orbitable 3D scene with mouse/touch controls."),
        ExperimentRegistration("LAB-024", fallback: "Bundled fictional room plus manual dimensions."),
        ExperimentRegistration("LAB-025", fallback: "Original procedural sample mesh and a supplied consented photo fixture."),
        ExperimentRegistration("LAB-026", fallback: "Original sample frames and explicit image import."),
        ExperimentRegistration("LAB-027", fallback: "Stereo mix and visible scene controls."),
        ExperimentRegistration("LAB-028", fallback: "Select reference clip and time manually."),
        ExperimentRegistration("LAB-029", fallback: "Offline audio-file processing and on-screen MIDI events."),
        ExperimentRegistration("LAB-030", fallback: "Visual pulse and optional quiet audio."),
        ExperimentRegistration("LAB-031", fallback: "In-app local playback using a small universally supported fixture."),
        ExperimentRegistration("LAB-032", fallback: "Keep the job foreground; Mac worker only while explicitly running."),
        ExperimentRegistration("LAB-033", fallback: "Import an original screen recording."),
        ExperimentRegistration("LAB-034", fallback: "Native TV display plus a synthetic camera fixture."),
        ExperimentRegistration("LAB-035", fallback: "Semantic list/table and standard platform controls."),
        ExperimentRegistration("LAB-036", fallback: "Synthetic replay supports the complete UI without HealthKit access."),
        ExperimentRegistration("LAB-037", fallback: "Deterministic fictional home with no real accessories."),
        ExperimentRegistration("LAB-038", fallback: "Local pass preview and sample event card."),
        ExperimentRegistration("LAB-039", fallback: "Web information page or full-app deep link, with no forced installation promise."),
        ExperimentRegistration("LAB-040", fallback: "Local transaction-state simulator."),
        ExperimentRegistration("LAB-041", fallback: "Local authorization and a clearly labeled passkey protocol simulation."),
        ExperimentRegistration("LAB-042", fallback: "Standard menu command and file import."),
        ExperimentRegistration("LAB-043", fallback: "In-app agenda and timers visible while foregrounded."),
        ExperimentRegistration("LAB-044", fallback: "Local shared-device or LAN play."),
        ExperimentRegistration("LAB-045", fallback: "Mouse/touch annotations and typed notes."),
        ExperimentRegistration("LAB-046", fallback: "Basic unlit renderer or recorded original preview labeled as a preview."),
        ExperimentRegistration("LAB-047", fallback: "Software peripheral simulator and a contract-level test suite."),
        ExperimentRegistration("LAB-048", fallback: "In-app protocol/lifecycle demonstrators labeled as simulations."),
    ]
}
